* evil-cutlass

Override delete operations to not affect the clipboard. Evil port of [[https://github.com/svermeulen/vim-cutlass][vim-cutlass]].

Every command that uses =evil-delete= except =evil-visual-paste= would use the the blackhole register by default, making them delete instead of cut. This includes:

- =c= and =cc= (evil-change)
- =C= (evil-change-line)
- =S= (evil-change-whole-line)
- =s= (evil-substitute)
- =d= and =dd= (evil-delete)
- =X= (evil-delete-backward-char)
- =x= (evil-delete-char)
- =D= (evil-delete-line)
- =C-u= (evil-delete-whole-line)

="= (evil-use-register) still works while evil-cutlass is active.

Selecting text in visual state then pasting over it runs =evil-visual-paste=, which also modifies the clipboard, but this behavior can already be controlled by =evil-kill-on-visual-paste=.

** Setup

#+begin_src emacs-lisp
(straight-use-package '(evil-cutlass :repo "https://github.com/kisaragi-hiu/evil-cutlass"))
(evil-cutlass-mode)
#+end_src

Now =x= will cut text into the default register (like =d= originally), while other evil commands will not edit the register by default.

="= (=evil-use-register=) still works, so ="adw= still cuts the word into the a register.

** Acknowledgments

- https://github.com/svermeulen/vim-cutlass :: original
- https://github.com/edkolev/evil-goggles :: I copied how it advises evil commands
